[package]
name = "is-thirteen"
version = "0.1.0"
edition = "2018"
description = "reserved"
license = "MIT"

[dependencies]
phf = { version = "0.9", features = ["macros"] }

[dev-dependencies]
rstest = "0.10"