name: test
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: rustup update
      - run: rustup component add clippy
      - run: rustup component add rustfmt
      - run: RUST_BACKTRACE=1 cargo test --all-features -- --nocapture
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo fmt -- --check